spring.application.name=publicapi

spring.output.ansi.enabled=always

logging.level.root=info

# OpenAPI 관련 서버 정보
# 개발자가 추가 생성한 설정정보
redtable.service-key=13fmLtfqBZiuZEetW8u6zbeQmj9qBEgYicSdxhjmiinS6xowEnJqbKkO5gHaj4bZ
redtable.base-url=https://busan-food.openapi.redtable.global