/*
 * This source file was generated by the Gradle 'init' task
 */
package ex02_syntax;

public class App {
    public static void main(String[] args) {
        int a;
        float b;
        double c;
        String d;
        boolean e;
        long f;
        char g;

        System.out.println("Hello, Java!");
    }
}
